
# SEO settings
title: "jay"
title2: "Log" # default: ""
description: "Hello World."
keywords: "Namyoon, Kim, jayLog, AUT, Machine Learning, Tensorflow, Unity, Development"
url: http://jaynerd.github.io # site url
baseurl: "" # apply repo name if use it under gh-pages branch
# baseurl: null # apply null if repo name is something like username.github.io

google_analytics: UA-XXXXX-XX
repo: http://github.com/jaynerd/jaynerd.github.io
disqus_shortname: ""
twitter_username: ""
comments: false

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "Namyoon"
  job      : "CS student"
  bio      : ""
  thumb    : /images/author.jpg
  email    : j4yn3rd@gmail.com
  url      : jaynerd.github.io
  github   : github.com/jaynerd
  twitter  : 
  facebook : facebook.com/namyoon.bryan.kim
  linkedin : linkedin.com/in/namyoon

# social settings
og_locale: "en_US"
twitter_card: ""
twitter_site: ""

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
